### ISSUE TITLE
Page page autres ressources ne semble pas cohérente avec le menu déroulant

### ISSUE THREAD

**Issue by Monstermanu** [ansforge/IG-fhir-telesurveillance#12]
La page https://ansforge.github.io/IG-fhir-telesurveillance/main/ig/autres_ressources.html est vide alors que le menu déroulant indique qu'il devrait y avoir au moins le lien vers les téléchargements (ce qui est représenté dans la table des matières) et les liens vers les spécifications FHIR et le site de l'ANS.

D'ailleurs ne faudrait-il pas mettre également le lien vers le site d'Interop'Santé qui est indiqué comme auteur?

**Comment by nriss** [comment]
La page autres_ressources n'est pas accessible normalement, c'est juste une page indispensable pour avoir un menu déroulant, je vais bricoler qqc pour qu'elle n'apparaisse pas vide:)
