### ISSUE TITLE
Visibilité d'InteropSanté effacée

### ISSUE THREAD

**Issue by fmacary** [ansforge/IG-fhir-telesurveillance#19]
## Description du problème
Le logo d'InteropSanté a disparu de la page d'accueil. 

## Fichier•s concerné•s
https://ansforge.github.io/IG-fhir-telesurveillance/main/ig/#accueil

## Solution proposée
Remettre le logo sur la page d'accueil en le faisant précéder de la phrase : "Ce guide a été élaboré sur la base des travaux du GT Télésurveillance d’InteropSanté auquel participe l'ANS."

**Comment by nriss** [comment]
Rajouté ici! :)
https://github.com/ansforge/IG-fhir-telesurveillance/pull/20

J'ai creusé pour comprendre ce qui s'est passé, je pense qu'en essayant de résoudre des conflits j'ai oublié de reprendre le paragraphe dans la PR #15  

J'ai également rajouté le lien vers le site d'InteropSanté dans le header lors de la PR #15
![image](https://github.com/ansforge/IG-fhir-telesurveillance/assets/48218773/c159e9fc-4250-4759-9c71-97476e2b002a)
